apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: NodePort
  selector:
    app: flask 
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.service.port }}
